WebSimulator.define do
	create(:road){|t| t.pos( x: 13, y: 6 )}
	create(:road){|t| t.pos( x: 14, y: 6 )}
	create(:road){|t| t.pos( x: 15, y: 6 )}
	create(:road){|t| t.pos( x: 16, y: 6 )}
	create(:road){|t| t.pos( x: 17, y: 6 )}
	create(:road){|t| t.pos( x: 18, y: 6 )}
	create(:road){|t| t.pos( x: 19, y: 6 )}
	create(:road){|t| t.pos( x: 20, y: 6 )}
	create(:road){|t| t.pos( x: 21, y: 6 )}
	create(:road){|t| t.pos( x: 22, y: 6 )}
	create(:road){|t| t.pos( x: 23, y: 6 )}
	create(:road){|t| t.pos( x: 24, y: 6 )}
	create(:road){|t| t.pos( x: 25, y: 6 )}
	create(:road){|t| t.pos( x: 26, y: 6 )}
	create(:road){|t| t.pos( x: 27, y: 6 )}
	create(:road){|t| t.pos( x: 28, y: 6 )}
	create(:road){|t| t.pos( x: 29, y: 6 )}
	create(:road){|t| t.pos( x: 30, y: 6 )}
	create(:road){|t| t.pos( x: 31, y: 6 )}
	create(:road){|t| t.pos( x: 32, y: 6 )}
	create(:road){|t| t.pos( x: 33, y: 6 )}
	create(:road){|t| t.pos( x: 33, y: 7 )}
	create(:road){|t| t.pos( x: 33, y: 8 )}
	create(:road){|t| t.pos( x: 33, y: 9 )}
	create(:start){|t| t.pos( x: 10, y: 10 )}
	create(:end){|t| t.pos( x: 20, y: 10 )}
	create(:road){|t| t.pos( x: 33, y: 10 )}
	create(:road){|t| t.pos( x: 33, y: 11 )}
	create(:road){|t| t.pos( x: 33, y: 12 )}
	create(:road){|t| t.pos( x: 33, y: 13 )}
	create(:road){|t| t.pos( x: 33, y: 14 )}
	create(:road){|t| t.pos( x: 33, y: 15 )}
	create(:road){|t| t.pos( x: 33, y: 16 )}
	create(:car){|t| t.pos( x: 27, y: 17 )}
	create(:car){|t| t.pos( x: 33, y: 13 )}
	create(:car){|t| t.pos( x: 33, y: 15 )}
	create(:car){|t| t.pos( x: 33, y: 11 )}
end
