WebSimulator.define do
	create(:tree){|t| t.pos( x: 9, y: 11 )}
	create(:tree){|t| t.pos( x: 10, y: 11 )}
	create(:tree){|t| t.pos( x: 11, y: 11 )}
	create(:tree){|t| t.pos( x: 12, y: 11 )}
	create(:tree){|t| t.pos( x: 13, y: 11 )}
	create(:tree){|t| t.pos( x: 14, y: 11 )}
	create(:tree){|t| t.pos( x: 15, y: 11 )}
	create(:tree){|t| t.pos( x: 16, y: 11 )}
	create(:tree){|t| t.pos( x: 17, y: 11 )}
	create(:tree){|t| t.pos( x: 18, y: 11 )}
	create(:tree){|t| t.pos( x: 19, y: 11 )}
	create(:tree){|t| t.pos( x: 20, y: 11 )}
	create(:tree){|t| t.pos( x: 21, y: 11 )}
	create(:tree){|t| t.pos( x: 22, y: 11 )}
	create(:tree){|t| t.pos( x: 23, y: 11 )}
	create(:tree){|t| t.pos( x: 24, y: 11 )}
	create(:tree){|t| t.pos( x: 25, y: 11 )}
	create(:tree){|t| t.pos( x: 26, y: 11 )}
	create(:tree){|t| t.pos( x: 27, y: 11 )}
	create(:tree){|t| t.pos( x: 28, y: 11 )}
	create(:tree){|t| t.pos( x: 29, y: 11 )}
	create(:tree){|t| t.pos( x: 30, y: 11 )}
	create(:tree){|t| t.pos( x: 31, y: 11 )}
	create(:tree){|t| t.pos( x: 31, y: 12 )}
	create(:tree){|t| t.pos( x: 6, y: 13 )}
	create(:tree){|t| t.pos( x: 7, y: 13 )}
	create(:tree){|t| t.pos( x: 8, y: 13 )}
	create(:tree){|t| t.pos( x: 9, y: 13 )}
	create(:tree){|t| t.pos( x: 10, y: 13 )}
	create(:tree){|t| t.pos( x: 31, y: 13 )}
	create(:tree){|t| t.pos( x: 3, y: 14 )}
	create(:tree){|t| t.pos( x: 10, y: 14 )}
	create(:tree){|t| t.pos( x: 31, y: 14 )}
	create(:tree){|t| t.pos( x: 3, y: 15 )}
	create(:tree){|t| t.pos( x: 10, y: 15 )}
	create(:tree){|t| t.pos( x: 31, y: 15 )}
	create(:tree){|t| t.pos( x: 10, y: 16 )}
	create(:tree){|t| t.pos( x: 11, y: 16 )}
	create(:tree){|t| t.pos( x: 31, y: 16 )}
	create(:tree){|t| t.pos( x: 2, y: 17 )}
	create(:tree){|t| t.pos( x: 3, y: 17 )}
	create(:tree){|t| t.pos( x: 11, y: 17 )}
	create(:tree){|t| t.pos( x: 32, y: 17 )}
	create(:tree){|t| t.pos( x: 3, y: 18 )}
	create(:tree){|t| t.pos( x: 4, y: 18 )}
	create(:tree){|t| t.pos( x: 5, y: 18 )}
	create(:tree){|t| t.pos( x: 10, y: 18 )}
	create(:tree){|t| t.pos( x: 32, y: 18 )}
	create(:tree){|t| t.pos( x: 6, y: 19 )}
	create(:tree){|t| t.pos( x: 10, y: 19 )}
	create(:tree){|t| t.pos( x: 31, y: 19 )}
	create(:tree){|t| t.pos( x: 32, y: 19 )}
	create(:tree){|t| t.pos( x: 7, y: 20 )}
	create(:tree){|t| t.pos( x: 10, y: 20 )}
	create(:tree){|t| t.pos( x: 11, y: 20 )}
	create(:tree){|t| t.pos( x: 12, y: 20 )}
	create(:tree){|t| t.pos( x: 13, y: 20 )}
	create(:tree){|t| t.pos( x: 14, y: 20 )}
	create(:tree){|t| t.pos( x: 15, y: 20 )}
	create(:tree){|t| t.pos( x: 16, y: 20 )}
	create(:tree){|t| t.pos( x: 17, y: 20 )}
	create(:tree){|t| t.pos( x: 18, y: 20 )}
	create(:tree){|t| t.pos( x: 19, y: 20 )}
	create(:tree){|t| t.pos( x: 20, y: 20 )}
	create(:tree){|t| t.pos( x: 21, y: 20 )}
	create(:tree){|t| t.pos( x: 22, y: 20 )}
	create(:tree){|t| t.pos( x: 23, y: 20 )}
	create(:tree){|t| t.pos( x: 24, y: 20 )}
	create(:tree){|t| t.pos( x: 25, y: 20 )}
	create(:tree){|t| t.pos( x: 26, y: 20 )}
	create(:tree){|t| t.pos( x: 27, y: 20 )}
	create(:tree){|t| t.pos( x: 28, y: 20 )}
	create(:tree){|t| t.pos( x: 29, y: 20 )}
	create(:tree){|t| t.pos( x: 30, y: 20 )}
	create(:tree){|t| t.pos( x: 31, y: 20 )}
end
