WebSimulator.define do
	create(:road){|t| t.pos( x: 3, y: 3 )}
	create(:road){|t| t.pos( x: 4, y: 3 )}
	create(:road){|t| t.pos( x: 5, y: 3 )}
	create(:road){|t| t.pos( x: 6, y: 3 )}
	create(:road){|t| t.pos( x: 7, y: 3 )}
	create(:road){|t| t.pos( x: 8, y: 3 )}
	create(:road){|t| t.pos( x: 9, y: 3 )}
	create(:road){|t| t.pos( x: 10, y: 3 )}
	create(:road){|t| t.pos( x: 11, y: 3 )}
	create(:road){|t| t.pos( x: 3, y: 4 )}
	create(:road){|t| t.pos( x: 11, y: 4 )}
	create(:road){|t| t.pos( x: 3, y: 5 )}
	create(:road){|t| t.pos( x: 11, y: 5 )}
	create(:road){|t| t.pos( x: 12, y: 5 )}
	create(:road){|t| t.pos( x: 13, y: 5 )}
	create(:road){|t| t.pos( x: 14, y: 5 )}
	create(:road){|t| t.pos( x: 15, y: 5 )}
	create(:road){|t| t.pos( x: 16, y: 5 )}
	create(:road){|t| t.pos( x: 17, y: 5 )}
	create(:road){|t| t.pos( x: 18, y: 5 )}
	create(:road){|t| t.pos( x: 19, y: 5 )}
	create(:road){|t| t.pos( x: 20, y: 5 )}
	create(:road){|t| t.pos( x: 21, y: 5 )}
	create(:road){|t| t.pos( x: 22, y: 5 )}
	create(:road){|t| t.pos( x: 23, y: 5 )}
	create(:road){|t| t.pos( x: 24, y: 5 )}
	create(:road){|t| t.pos( x: 25, y: 5 )}
	create(:road){|t| t.pos( x: 26, y: 5 )}
	create(:road){|t| t.pos( x: 27, y: 5 )}
	create(:road){|t| t.pos( x: 28, y: 5 )}
	create(:road){|t| t.pos( x: 29, y: 5 )}
	create(:road){|t| t.pos( x: 30, y: 5 )}
	create(:road){|t| t.pos( x: 31, y: 5 )}
	create(:road){|t| t.pos( x: 32, y: 5 )}
	create(:road){|t| t.pos( x: 33, y: 5 )}
	create(:road){|t| t.pos( x: 34, y: 5 )}
	create(:road){|t| t.pos( x: 35, y: 5 )}
	create(:road){|t| t.pos( x: 36, y: 5 )}
	create(:road){|t| t.pos( x: 37, y: 5 )}
	create(:road){|t| t.pos( x: 38, y: 5 )}
	create(:road){|t| t.pos( x: 39, y: 5 )}
	create(:road){|t| t.pos( x: 40, y: 5 )}
	create(:road){|t| t.pos( x: 41, y: 5 )}
	create(:road){|t| t.pos( x: 42, y: 5 )}
	create(:road){|t| t.pos( x: 43, y: 5 )}
	create(:road){|t| t.pos( x: 44, y: 5 )}
	create(:road){|t| t.pos( x: 45, y: 5 )}
	create(:road){|t| t.pos( x: 46, y: 5 )}
	create(:road){|t| t.pos( x: 47, y: 5 )}
	create(:road){|t| t.pos( x: 48, y: 5 )}
	create(:road){|t| t.pos( x: 49, y: 5 )}
	create(:road){|t| t.pos( x: 50, y: 5 )}
	create(:road){|t| t.pos( x: 51, y: 5 )}
	create(:road){|t| t.pos( x: 52, y: 5 )}
	create(:road){|t| t.pos( x: 3, y: 6 )}
	create(:road){|t| t.pos( x: 52, y: 6 )}
	create(:road){|t| t.pos( x: 2, y: 7 )}
	create(:road){|t| t.pos( x: 3, y: 7 )}
	create(:start){|t| t.pos( x: 8, y: 7 )}
	create(:road){|t| t.pos( x: 52, y: 7 )}
	create(:road){|t| t.pos( x: 2, y: 8 )}
	create(:road){|t| t.pos( x: 52, y: 8 )}
	create(:road){|t| t.pos( x: 2, y: 9 )}
	create(:road){|t| t.pos( x: 52, y: 9 )}
	create(:road){|t| t.pos( x: 2, y: 10 )}
	create(:road){|t| t.pos( x: 3, y: 10 )}
	create(:road){|t| t.pos( x: 4, y: 10 )}
	create(:road){|t| t.pos( x: 5, y: 10 )}
	create(:road){|t| t.pos( x: 6, y: 10 )}
	create(:road){|t| t.pos( x: 7, y: 10 )}
	create(:road){|t| t.pos( x: 8, y: 10 )}
	create(:road){|t| t.pos( x: 52, y: 10 )}
	create(:road){|t| t.pos( x: 53, y: 10 )}
	create(:road){|t| t.pos( x: 8, y: 11 )}
	create(:road){|t| t.pos( x: 53, y: 11 )}
	create(:road){|t| t.pos( x: 8, y: 12 )}
	create(:road){|t| t.pos( x: 53, y: 12 )}
	create(:road){|t| t.pos( x: 8, y: 13 )}
	create(:road){|t| t.pos( x: 53, y: 13 )}
	create(:road){|t| t.pos( x: 8, y: 14 )}
	create(:road){|t| t.pos( x: 53, y: 14 )}
	create(:road){|t| t.pos( x: 8, y: 15 )}
	create(:road){|t| t.pos( x: 53, y: 15 )}
	create(:road){|t| t.pos( x: 8, y: 16 )}
	create(:road){|t| t.pos( x: 53, y: 16 )}
	create(:road){|t| t.pos( x: 8, y: 17 )}
	create(:road){|t| t.pos( x: 53, y: 17 )}
	create(:road){|t| t.pos( x: 8, y: 18 )}
	create(:road){|t| t.pos( x: 53, y: 18 )}
	create(:road){|t| t.pos( x: 8, y: 19 )}
	create(:road){|t| t.pos( x: 53, y: 19 )}
	create(:road){|t| t.pos( x: 8, y: 20 )}
	create(:road){|t| t.pos( x: 53, y: 20 )}
	create(:road){|t| t.pos( x: 8, y: 21 )}
	create(:road){|t| t.pos( x: 53, y: 21 )}
	create(:road){|t| t.pos( x: 8, y: 22 )}
	create(:end){|t| t.pos( x: 49, y: 22 )}
	create(:road){|t| t.pos( x: 53, y: 22 )}
	create(:road){|t| t.pos( x: 8, y: 23 )}
	create(:road){|t| t.pos( x: 53, y: 23 )}
	create(:road){|t| t.pos( x: 8, y: 24 )}
	create(:road){|t| t.pos( x: 53, y: 24 )}
	create(:road){|t| t.pos( x: 8, y: 25 )}
	create(:road){|t| t.pos( x: 53, y: 25 )}
	create(:road){|t| t.pos( x: 8, y: 26 )}
	create(:road){|t| t.pos( x: 53, y: 26 )}
	create(:road){|t| t.pos( x: 8, y: 27 )}
	create(:road){|t| t.pos( x: 53, y: 27 )}
	create(:road){|t| t.pos( x: 8, y: 28 )}
	create(:road){|t| t.pos( x: 36, y: 28 )}
	create(:road){|t| t.pos( x: 37, y: 28 )}
	create(:road){|t| t.pos( x: 38, y: 28 )}
	create(:road){|t| t.pos( x: 39, y: 28 )}
	create(:road){|t| t.pos( x: 40, y: 28 )}
	create(:road){|t| t.pos( x: 41, y: 28 )}
	create(:road){|t| t.pos( x: 42, y: 28 )}
	create(:road){|t| t.pos( x: 43, y: 28 )}
	create(:road){|t| t.pos( x: 44, y: 28 )}
	create(:road){|t| t.pos( x: 45, y: 28 )}
	create(:road){|t| t.pos( x: 46, y: 28 )}
	create(:road){|t| t.pos( x: 47, y: 28 )}
	create(:road){|t| t.pos( x: 48, y: 28 )}
	create(:road){|t| t.pos( x: 49, y: 28 )}
	create(:road){|t| t.pos( x: 50, y: 28 )}
	create(:road){|t| t.pos( x: 51, y: 28 )}
	create(:road){|t| t.pos( x: 52, y: 28 )}
	create(:road){|t| t.pos( x: 53, y: 28 )}
	create(:road){|t| t.pos( x: 8, y: 29 )}
	create(:road){|t| t.pos( x: 9, y: 29 )}
	create(:road){|t| t.pos( x: 10, y: 29 )}
	create(:road){|t| t.pos( x: 11, y: 29 )}
	create(:road){|t| t.pos( x: 12, y: 29 )}
	create(:road){|t| t.pos( x: 13, y: 29 )}
	create(:road){|t| t.pos( x: 14, y: 29 )}
	create(:road){|t| t.pos( x: 15, y: 29 )}
	create(:road){|t| t.pos( x: 16, y: 29 )}
	create(:road){|t| t.pos( x: 17, y: 29 )}
	create(:road){|t| t.pos( x: 18, y: 29 )}
	create(:road){|t| t.pos( x: 19, y: 29 )}
	create(:road){|t| t.pos( x: 20, y: 29 )}
	create(:road){|t| t.pos( x: 21, y: 29 )}
	create(:road){|t| t.pos( x: 22, y: 29 )}
	create(:road){|t| t.pos( x: 23, y: 29 )}
	create(:road){|t| t.pos( x: 24, y: 29 )}
	create(:road){|t| t.pos( x: 25, y: 29 )}
	create(:road){|t| t.pos( x: 26, y: 29 )}
	create(:road){|t| t.pos( x: 27, y: 29 )}
	create(:road){|t| t.pos( x: 28, y: 29 )}
	create(:road){|t| t.pos( x: 29, y: 29 )}
	create(:road){|t| t.pos( x: 30, y: 29 )}
	create(:road){|t| t.pos( x: 31, y: 29 )}
	create(:road){|t| t.pos( x: 32, y: 29 )}
	create(:road){|t| t.pos( x: 33, y: 29 )}
	create(:road){|t| t.pos( x: 34, y: 29 )}
	create(:road){|t| t.pos( x: 35, y: 29 )}
	create(:road){|t| t.pos( x: 36, y: 29 )}
	create(:car){|t| t.pos( x: 17, y: 5 )}
end
